name: absensi_madrasah
description: Aplikasi Absensi Digital Madrasah Ibtidaiyah Al-Amsar

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Networking
  dio: ^5.4.3
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^14.2.0
  
  # Utility
  intl: ^0.19.0
  fpdart: ^1.1.0
  google_fonts: ^6.2.1
  connectivity_plus: ^5.0.2
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  camera: 0.10.5
  image_picker: ^1.0.4
  path_provider: ^2.1.3
  mobile_scanner: 3.2.0
  flutter_svg: ^2.0.10
  flutter_tts: ^3.8.5

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.17
  geolocator_android: 4.2.0
  camera_android: 0.10.8
  image_picker_android: 0.8.8
  path_provider_android: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
